## This workflow runs manually.
##
## More details on https://docs.github.com/en/actions/writing-workflows/choosing-when-your-workflow-runs/events-that-trigger-workflows#workflow_dispatch

name: Manual Run

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      name:
        description: 'Name of the person to greet'
        required: true
        type: string
      specialGreeting:
        description: 'Ask for a special greeting?'
        required: false
        type: boolean

jobs:
  greet:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Hey ${{ inputs.name }}"
          echo "Special greeting: ${{ inputs.specialGreeting }}"
