## This workflow runs periodically.
##
## More details on https://docs.github.com/en/actions/writing-workflows/choosing-when-your-workflow-runs/events-that-trigger-workflows#schedule

name: Scheduled Workflow

on:
  schedule:
    - cron: '30 5 * * 1,3' # 5:30 AM on Monday and Wednesday
    - cron: '30 5 * * 2,4' # 5:30 AM on Tuesday and Thursday

jobs:
  test_schedule:
    runs-on: ubuntu-latest
    steps:
      - name: Not on Monday or Wednesday
        if: github.event.schedule != '30 5 * * 1,3'
        run: echo "This step will be skipped on Monday and Wednesday"
      - name: Every time
        run: echo "This step will always run"
