## This workflow runs on single or multiple events.
##
## More details on https://docs.github.com/en/actions/writing-workflows/choosing-when-your-workflow-runs/events-that-trigger-workflows

name: Single vs Multiple Trigger

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  label:
    types:
      - created
  issues:
    types:
      - opened
      - labeled

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: echo "Hello Build! Triggered by ${{ github.event_name }} event."



