# This workflow will build a Java project with Maven
##
## More details on https://docs.github.com/en/actions/use-cases-and-examples/building-and-testing/building-and-testing-java-with-maven

name: Build a Java Application with checkstyle

on:
  push:
    branches: [ "main" ]
    paths:
      - java-app/**
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    defaults:
      run:
        # Set the working directory to the java-app directory
        # works only for the shell.
        working-directory: java-app
    outputs:
        checkstyle-report: ${{ steps.checkstyle.outputs.checkstyle-report }}
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven
    - name: Run Code Quality Action
      id: checkstyle
      uses: ./.github/actions/code-quality-java
      with:
        working-directory: java-app
  log-output:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Print the output
        run: |
          echo "The output is ${{ needs.build.outputs.checkstyle-report }}"
