## This workflow shows how to access workflow context.
##
## More details on https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/accessing-contextual-information-about-workflow-runs

name: Context testing
on: push

jobs:
  dump_contexts_to_log:
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: Dump job context
        env:
          JOB_CONTEXT: ${{ toJson(job) }}
        run: echo "$JOB_CONTEXT"
        # steps must have an id to be included in the context
      - id: step_generate_random_number
        name: Generate a random number
        run: |
          number=$((RANDOM))
          echo "number=$number" >> "$GITHUB_OUTPUT"
      - name: Assign token to a variable
        run: |
          MY_CUSTOM_TOKEN="${{ github.token }}"
          echo "My custom token is: $MY_CUSTOM_TOKEN"  # Do not do this!
      - name: Set token as output
        run: echo "myToken=${{ github.token }}" >> $GITHUB_OUTPUT  # Avoid this!
      - name: Write token to a file
        run: |
          echo "${{ github.token }}" > secret.txt
          cat secret.txt  # This would reveal the token!
      - name: Dump steps context
        env:
          STEPS_CONTEXT: ${{ toJson(steps) }}
        run: echo "$STEPS_CONTEXT"
