name: Multiple Trigger

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  label:
    types:
      - created
  issues:
    types:
      - opened
      - labeled

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: echo "Hello Build! Triggered by ${{ github.event_name }} event."
